import type { PromptSectionProvider } from "../../contracts/plugins/plugin-registrar";
import { createResolvedFragmentDraft, createResolvedSectionDraft } from "../../contracts/plugins/create-resolved-section-draft";

const BASELINE_DE = "LOCATION, WETTER & LICHT\nin einer modernen Wohnung, im Bereich Wohnzimmer · modern, mit natürlichem Fenster. Die Szene wirkt ruhig und alltäglich. Die Umgebung ist trocken, ohne Nässe-Effekt. Die Bildstimmung wirkt ruhig, ausgeglichen und alltäglich. Es ist trocken und mild, bei Windstille und klar. ein leicht versetztes Sofakissen. ein beiläufig abgelegtes Buch oder Magazin. Vorhangfalten mit kleinen natürlichen Unterschieden. ein nicht exakt mittig ausgerichteter Beistelltisch. Fensterlicht bestimmt gemeinsam die Richtung von Haut-Highlights, Stoffreflexionen, Haarlicht und Schlagschatten. weiche Übergänge besitzen breite Halbschatten und keine widersprüchlichen harten Zweitschatten. kleine nicht-periodische Unregelmäßigkeiten statt wiederholter Muster. dezente Gebrauchsspuren nur dort, wo Material und Nutzung sie plausibel machen. Hintergrundobjekte besitzen konsistente Maßstäbe, Fluchtlinien und gegenseitige Verdeckung. Fensterlicht fällt seitlich ein, wirkt weich und erzeugt weich definierte Schatten bei geringem Kontrast. neutraler Weißabgleich mit natürlichen Hautfarben.";
const BASELINE_EN = "LOCATION, WEATHER, AND LIGHT\nThe scene is set in an apartment, specifically a modern living room with natural window light. The mood feels calm, balanced, naturally neutral, everyday, and unposed. Conditions are dry and mild, with calm winds and clear air. The environment is dry, without a wet-look effect. Visible environmental details include a slightly offset cushion, a casually placed book or magazine, curtain folds with small natural differences, a side table that is not perfectly centered, small non-periodic irregularities rather than repeated patterns, subtle signs of use only where material and function make them plausible, and background objects with consistent scale, perspective lines, and mutual occlusion. Window light comes from the side, appears soft, and creates softly defined shadows with low contrast. The image uses a neutral white balance with natural skin tones.";

export const sceneLightingSection: PromptSectionProvider = {
  id: "scene-lighting",
  provide: (state) => {
    const german = state.facts.values.promptLanguage === "Deutsch";
    const requiredPaths = ["scene.area", "scene.atmosphere", "scene.location", "scene.mood", "scene.surfaceCondition", "lighting.setup", "lighting.source", "lighting.whiteBalance"] as const;
    const hasCompleteBaseline = requiredPaths.every((path) => state.trace.entries.some((entry) => entry.path === path));
    const fragments = !hasCompleteBaseline ? undefined : german ? [
      createResolvedFragmentDraft(state, "scene-lighting", "scene.environment", "in einer modernen Wohnung, im Bereich Wohnzimmer · modern, mit natürlichem Fenster. Die Szene wirkt ruhig und alltäglich. Die Umgebung ist trocken, ohne Nässe-Effekt. Die Bildstimmung wirkt ruhig, ausgeglichen und alltäglich. Es ist trocken und mild, bei Windstille und klar.", ["scene.area", "scene.location", "scene.mood", "scene.surfaceCondition"]),
      createResolvedFragmentDraft(state, "scene-lighting", "scene.natural-details", "ein leicht versetztes Sofakissen. ein beiläufig abgelegtes Buch oder Magazin. Vorhangfalten mit kleinen natürlichen Unterschieden. ein nicht exakt mittig ausgerichteter Beistelltisch.", ["scene.atmosphere"]),
      createResolvedFragmentDraft(state, "scene-lighting", "lighting.coordination", "Fensterlicht bestimmt gemeinsam die Richtung von Haut-Highlights, Stoffreflexionen, Haarlicht und Schlagschatten. weiche Übergänge besitzen breite Halbschatten und keine widersprüchlichen harten Zweitschatten.", ["lighting.setup", "lighting.source"]),
      createResolvedFragmentDraft(state, "scene-lighting", "scene.surface-details", "kleine nicht-periodische Unregelmäßigkeiten statt wiederholter Muster. dezente Gebrauchsspuren nur dort, wo Material und Nutzung sie plausibel machen. Hintergrundobjekte besitzen konsistente Maßstäbe, Fluchtlinien und gegenseitige Verdeckung.", ["scene.atmosphere"]),
      createResolvedFragmentDraft(state, "scene-lighting", "lighting.capture", "Fensterlicht fällt seitlich ein, wirkt weich und erzeugt weich definierte Schatten bei geringem Kontrast.", ["lighting.setup", "lighting.source"]),
      createResolvedFragmentDraft(state, "scene-lighting", "lighting.white-balance", "neutraler Weißabgleich mit natürlichen Hautfarben.", ["lighting.whiteBalance"]),
    ] : [
      createResolvedFragmentDraft(state, "scene-lighting", "scene.environment", "The scene is set in an apartment, specifically a modern living room with natural window light. The mood feels calm, balanced, naturally neutral, everyday, and unposed. Conditions are dry and mild, with calm winds and clear air. The environment is dry, without a wet-look effect.", ["scene.area", "scene.location", "scene.mood", "scene.surfaceCondition"]),
      createResolvedFragmentDraft(state, "scene-lighting", "scene.natural-details", "Visible environmental details include a slightly offset cushion, a casually placed book or magazine, curtain folds with small natural differences, a side table that is not perfectly centered, small non-periodic irregularities rather than repeated patterns, subtle signs of use only where material and function make them plausible, and background objects with consistent scale, perspective lines, and mutual occlusion.", ["scene.atmosphere"]),
      createResolvedFragmentDraft(state, "scene-lighting", "lighting.capture", "Window light comes from the side, appears soft, and creates softly defined shadows with low contrast.", ["lighting.setup", "lighting.source"]),
      createResolvedFragmentDraft(state, "scene-lighting", "lighting.white-balance", "The image uses a neutral white balance with natural skin tones.", ["lighting.whiteBalance"]),
    ];
    return [createResolvedSectionDraft(state, "scene-lighting", german ? BASELINE_DE : BASELINE_EN, fragments)];
  },
};
